name = "FormalSnarksProject"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FormalSnarksProject"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "smt"
scope = "ufmg-smite"
rev = "main"

[[lean_lib]]
name = "FormalSnarksProject"
