import FormalSnarksProject.Models.StraightforwardAGMProofSystem
import FormalSnarksProject.ToMathlib.COrdMvPolynomialRepr

/-!
# Generic SMT-LIB (`QF_FF`) export of ideal-membership problems

Shared machinery for turning an `AGMProofSystemInstantiation.IdealMembershipProblem` into an
SMT-LIB 2.6 benchmark file in the finite-field theory (`QF_FF`), used by the per-SNARK export
scripts (`Groth16TypeIII/SMTExport.lean`, `ToySnark/SMTExport.lean`).

## What the emitted query means

The soundness problem asks whether the `target` polynomial lies in the **radical** of the ideal
generated by `generators` (over the problem's variables). By the (weak) Nullstellensatz this is
equivalent to: the target vanishes at every common zero of the generators. So the SMT encoding is
the search for a counterexample — a *cheating assignment*:

    ∃ (assignment of the variables) .  (⋀ᵢ generatorᵢ = 0)  ∧  target ≠ 0

**`unsat` ⟺ the target is in the radical ⟺ soundness holds.** A `sat` result would be a
concrete break.

## Field

The math is over an arbitrary field (all coefficients are `0`/`±1`), so the modulus is a free
choice. We target the **BN254 / alt-bn128 scalar field** prime `r`, the standard modulus in ZK
tooling, so the instances sit in the same family as real proof-system benchmarks.

Computation is done over `ZMod 101` (a small field where the pipelines are `#eval`-able); each
coefficient is lifted back to a signed integer `{-50,…,50}` (which recovers the true `0/±1`
coefficients exactly) and re-emitted as a BN254 field literal. `writeProblem` aborts if any
coefficient falls outside that window, so the lift is never silently lossy.

Variable names are obtained from the `Repr` of the problem's variable type, sanitized into
SMT-LIB simple symbols (spaces to underscores, Greek letters spelled out).
-/

open CPoly CPoly.COrdMvPolynomial

namespace SMT

instance : Fact (Nat.Prime 101) := ⟨by norm_num⟩

/-- The field the problems are computed over (small, so everything is `#eval`-able). -/
abbrev F := ZMod 101

/-- The BN254 (alt-bn128) scalar-field prime `r`, the SMT-LIB finite-field order. -/
def bn254 : String :=
  "21888242871839275222246405745257275088548364400416034343698204186575808495617"

/-! ### Rendering variable names -/

/-- Turn one character of a variable's readable `repr` into an SMT-LIB-safe simple-symbol fragment
(spaces to underscores, Greek toxic-waste letters spelled out). -/
def sanitizeChar : Char → String
  | ' ' => "_"
  | 'α' => "alpha"
  | 'β' => "beta"
  | 'γ' => "gamma"
  | 'δ' => "delta"
  | c => String.singleton c

variable {V : Type} [FinEnum V] [Ord V] [Std.TransOrd V] [Std.LawfulEqOrd V] [Repr V]

/-- The SMT-LIB symbol for a variable, e.g. `comp_G1_C_q_u_wit`, `single_G2_B_delta`. -/
def smtVarName (v : V) : String :=
  (reprStr v).foldl (fun acc c => acc ++ sanitizeChar c) ""

/-! ### Rendering coefficients -/

/-- Lift a `ZMod 101` coefficient to its signed representative in `{-50,…,50}`. -/
def signedCoeff (c : F) : Int :=
  let n : Int := (c.val : Int)
  if n ≤ 50 then n else n - 101

/-- Render a signed integer coefficient as an SMT-LIB finite-field literal of sort `F`. -/
def smtCoeff (n : Int) : String :=
  if n ≥ 0 then s!"(as ff{n} F)"
  else s!"(ff.neg (as ff{-n} F))"

/-! ### Rendering polynomials -/

/-- The factors of a monomial as a list of variable symbols, repeated by exponent
(e.g. `x^2 * y ↦ [x, x, y]`). -/
def monomialAtoms (m : COrdMvMonomial V) : List String :=
  (FinEnum.toList V).foldr (fun v acc =>
    (List.replicate (COrdMvMonomial.degreeOf m v) (smtVarName v)) ++ acc) []

/-- Render a single term `c · m` as an SMT-LIB expression of sort `F`. -/
def smtTerm (m : COrdMvMonomial V) (c : F) : String :=
  let n := signedCoeff c
  let factors := monomialAtoms m
  -- Drop a coefficient of `1` when there is at least one variable factor.
  let atoms := if n = 1 ∧ ¬ factors.isEmpty then factors else smtCoeff n :: factors
  match atoms with
  | [] => "(as ff0 F)"            -- unreachable: a stored monomial has nonzero coeff
  | [a] => a
  | _ => "(ff.mul " ++ String.intercalate " " atoms ++ ")"

/-- Render a whole polynomial as an SMT-LIB expression of sort `F` (a sum of its terms). -/
def smtPoly (p : COrdMvPolynomial V F) : String :=
  match (OrdLawful.monomials p).map (fun m => smtTerm m (coeff m p)) with
  | [] => "(as ff0 F)"
  | [t] => t
  | terms => "(ff.add " ++ String.intercalate " " terms ++ ")"

/-! ### Assembling the file -/

/-- The variables actually occurring in the target or some generator. -/
def usedVars (prob : AGMProofSystemInstantiation.IdealMembershipProblem V F) : List V :=
  let polys := prob.target :: prob.generators
  (FinEnum.toList V).filter (fun v =>
    polys.any (fun p => (OrdLawful.monomials p).any (fun m => COrdMvMonomial.degreeOf m v ≠ 0)))

/-- The full SMT-LIB 2.6 benchmark file. `sourceInfo` goes into `(set-info :source |…|)`;
`targetComment` describes the target dis-equation. -/
def smtFile (prob : AGMProofSystemInstantiation.IdealMembershipProblem V F)
    (sourceInfo targetComment : String) : String :=
  let header :=
    "(set-info :smt-lib-version 2.6)\n" ++
    "(set-logic QF_FF)\n" ++
    s!"(set-info :source |{sourceInfo}|)\n" ++
    "(set-info :category \"crafted\")\n" ++
    "(set-info :status unknown)\n" ++
    s!"(define-sort F () (_ FiniteField {bn254}))\n"
  let decls := String.join <|
    (usedVars prob).map (fun v => s!"(declare-fun {smtVarName v} () F)\n")
  let genAsserts := String.join <|
    prob.generators.map (fun g => s!"(assert (= {smtPoly g} (as ff0 F)))\n")
  let targetAssert := s!"(assert (not (= {smtPoly prob.target} (as ff0 F))))\n"
  header ++ "\n" ++ decls ++ "\n" ++
    s!"; {prob.generators.length} generator equations (verifier toxic-waste coefficients)\n" ++
    genAsserts ++
    s!"\n; {targetComment}\n" ++
    targetAssert ++
    "\n(check-sat)\n"

/-- Sanity guard: every coefficient lifts into the `{-50,…,50}` window, so re-emitting the
`ZMod 101` computation over BN254 is faithful. -/
def coeffsInRange (prob : AGMProofSystemInstantiation.IdealMembershipProblem V F) : Bool :=
  let polys := prob.target :: prob.generators
  polys.all (fun p => (OrdLawful.monomials p).all (fun m =>
    let n := signedCoeff (coeff m p)
    decide (-50 ≤ n) && decide (n ≤ 50)))

/-- Write the benchmark file for `prob` to `path`, after checking the coefficient lift is
faithful. -/
def writeProblem (prob : AGMProofSystemInstantiation.IdealMembershipProblem V F)
    (path sourceInfo targetComment : String) : IO Unit := do
  if ! coeffsInRange prob then
    throw <| IO.userError "A coefficient fell outside {-50,…,50}; the signed lift is lossy."
  IO.FS.writeFile path (smtFile prob sourceInfo targetComment)
  IO.println
    s!"Wrote {path} ({prob.generators.length} generators, {(usedVars prob).length} variables)."

end SMT
